# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4053699e55eb2e164d69e3a346dd8c08bb1e44f9088552e6a279af94f3b1f8d835a68689b63cd5d77e26f7b55e422de4ebc35676800bd62232ef92c5276a251b

test:
  secret_key_base: c1aa798d1c3a2eed10fb101f64653abe35abdb634949d1f484b12a3904a112df23104e5180594df7d27236f74561a01da4dc5361d023c0eba8bf5a32b99c9d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
